# -*- coding: utf-8 -*-
"""expense tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPtTvAj8qlPYuvJQqIG1NzYte2NSKRaA
"""

from datetime import datetime
def get_input(prompt):
    value = input(prompt).strip()
    if value.lower() == "done":
        return "done"
    if value.lower() == "cancel":
        return "cancel"
    if not value:
         return "empty"
    return value
while True:
  print("Write your total expendale income: ")
  income_input = input().strip()
  try:
      income = float(income_input)
      if income <= 0:
          print("Income must be positive. Try again.")
          continue
      break
  except ValueError:
      print("Please enter a valid number. Try again.")

expenses={}
print("Enter expenes. Type 'done' to finish, ' cancel' to scrap current entry.")

while True:
    while True:
        date = get_input("Date of payment: ")
        if date == "done":
            break
        if date == "cancel":
            print("Entry cancelled.")
            break
        if date == "empty":
            print("Date cannot be empty.")
            continue
        try:
            datetime.strptime(date, "%d/%m/%Y")
            break
        except ValueError:
            print("Please enter date in DD/MM/YYYY format. Try again.")
    if date == "done":
          break
    if date =="cancel":
          continue
    while True:
          method = get_input("Payment method (UPI/Cash/Card): ")
          if method == "done":
              break
          if method == "cancel":
              print("Entry cancelled.")
              break
          if method == "empty":
              print("Payment method cannot be empty.")
              continue
          if method.lower() not in ["upi", "cash", "card"]:
              print("Please enter UPI, Cash, or Card only.")
              continue
          break
    if method == "done":
          break
    if method == "cancel":
          continue
    while True:
          paidto = get_input("Paid to: ")
          if paidto == "done":
              break
          if paidto == "cancel":
              print("Entry cancelled.")
              break
          if paidto == "empty":
              print("Paid to cannot be empty.")
              continue
          if any(char.isdigit() for char in paidto):
               print("Paid to should be a name.")
               continue
          break
    if paidto == "done":
          break
    if paidto == "cancel":
          continue
    while True:
          expense = get_input("Enter expense name(description): ")
          if expense == "done":
              break
          if expense == "cancel":
              print("Entry cancelled.")
              break
          if expense == "empty":
              print("Expense name cannot be empty.")
              continue
          break
    if expense == "done":
          break
    if expense == "cancel":
          continue
    while True:
          amount = get_input("Amount: ")
          if amount == "done":
              break
          if amount == "cancel":
              print("Entry cancelled.")
              break
          if amount == "empty":
              print("Amount cannot be empty.")
              continue
          try:
               amount = float(amount)
               if amount <= 0:
                   print("Amount must be positive. Try again.")
                   continue
               break
          except ValueError:
              print("Please enter a valid number. Try again.")
    if amount == "done":
        break
    if amount == "cancel":
        continue
    record = date, method.upper(), paidto.title(), expense.title(), str(amount)
    if expense not in expenses:
        expenses[expense] = []
    expenses[expense].append(record)
    print(f"Entry added successfully.")
total_spent = 0
for records in expenses.values():
    for record in records:
        total_spent += float(record[4])
remaining = income - total_spent
print("\n==================")
print("EXPENSE SUMMARY")
print("==================")
for category, records in expenses.items():
    print(f"\n{category}:")
    category_total = 0
    for record in records:
        print(f"  {record[0]} | {record[1]} | {record[2]} | ₹{record[4]}")
        category_total += float(record[4])
    print(f"  Category total: ₹{category_total}")

print("\n==================")
print(f"Total income: ₹{income}")
print(f"Total spent: ₹{total_spent}")

if remaining < 0:
    print(f"⚠️ Warning: You have overspent by ₹{abs(remaining)}!")
else:
    print(f"Remaining balance: ₹{remaining}")
print("==================")